### ISSUE TITLE
An AtariBasic syntax that you could adapt

### ISSUE THREAD

**Issue by thinkyhead** [marcin-jozwikowski/atari-basic-vsc-extension#1]
Greetings! I just discovered your VSCode extension for AtariBasic syntax. I wanted to let you know that I spent a bunch of time on making an AtariBasic syntax in Sublime Text format — which is based on tmLanguage, and maps pretty easily to it. I might try to convert my syntax over and send a PR, but in the meantime if you wanted to adapt any part of it, here is the actual file: https://github.com/thinkyhead/6502-Tools/blob/master/Sublime/AtariTools/AtariBASIC.sublime-syntax

It has some cool features. The syntax parser of TextMate/Sublime/VSCode is a lot like the actual AtariBasic parser itself, so it does a good job of highlighting syntax errors and missing parentheses in-place as you're editing.

The syntax might be missing some nuances, but it is pretty complete. Here is a demo of the syntax, styled appropriately with a custom theme: https://youtu.be/-hbXl8p8WLY?t=770

**Comment by marcin-jozwikowski** [comment]
Hi!

It's been over a year and there is no excuse for such long delay on my side. I'm sorry for that!

I'm also very thankful for your suggestion! I've already put your code to good use and will release a new version based on your work in next couple of days. VSCode is not capable of utilizing all the features that you've implemented in Sublime syntax (or I don't understand something, which is very much possible) but even in its limited scope it's way better than what I've made.

Thank you very much!
